### ISSUE TITLE
combotree combotreeValue 无法获取到值

### ISSUE THREAD

**Issue by Seaear** [wengys/knockout-easyui-LITE#1]

**Comment by wengys** [comment]
你好，
能否仔细描述下问题呢？最好能给个示例代码说明下问题。
本地测试easyui1.3.6与目前最新的1.4.1都工作正常。

**Comment by Seaear** [comment]
很奇怪，在我的项目中就是有问题，另外建的测试代码没有问题，在我的项目中我修改了一下代码问题解决了，第596行修改了一下
      options = $(element).combotree('options');
      comboOptions = $(element).combo('options');
      if (options.multiple === true) {
        options.onChange = refreshValueFun(options.onChange);
        options.multiple = false;
        $(element).combotree(options);
      } else {
        comboOptions.onChange = refreshValueFun(comboOptions.onChange);
        options.onChange = refreshValueFun(options.onChange);//加入这行
      }

**Comment by wengys** [comment]
你好，
或许是你的项目中有其他地方也对combotree所继承的combo的options进行了重写？这样的话倒是确实会发生自定义的onChange事件无法工作的问题。
我这本地测试过，正常监听onChange事件是没有问题的。而且看你加的那行也像是combo的options上重写的onChange事件处理方法失效了。
