### ISSUE TITLE
Get the whole item as idField?

### ISSUE THREAD

**Issue by abazanvillanueva** [wengys/knockout-easyui-LITE#3]
Is there any way to get the whole item as IdField instead of one single column like 'Code' for example?

**Comment by wengys** [comment]
If you want to get the whole item from combo or combobox or any combo-*, please just fork and modify as you wish, I can assure you it's pretty easy. I have limit ambition when writing this library, so many features is missing intentially. I can't tell will one day changed my mind, but for now it's OK.

If you want to ignore the idField, unfortunately EasyUI its self not always function well without an idField, actually in most case it will just use a default idField if not changed manually.
