### ISSUE TITLE
combobox绑定问题

### ISSUE THREAD

**Issue by JasonNii** [wengys/knockout-easyui-LITE#4]
jquery-1.11.3和jquery-easyui-1.5.2下，第一次选择后value值不变，第二次选择value值变了，但是value值是上次选择的值

**Comment by wengys** [comment]
确实有问题，已复现

**Comment by wengys** [comment]
已修复，jeasyui 1.5和1.4相比，setValues后立即getValues，返回的值还是setValues之前的。
